### ISSUE TITLE
IDEA : possibility to resize the GUI modules 

### ISSUE THREAD

**Issue by ShyButterfly** [hannibal00212/SkyHanni#100]
All is in the title, i need (and maybe a lot of players) a lot of gui modules for tracking farming sessions, pet progression, cultivating on my hoe etc 
But all the gui is too big for my screen, and its a mess when all is displayed, so i purpose this idea !
(sorry for my broken english, its not my main language) 

Have a nice day all !

**Comment by hannibal002** [comment]
Hey, thanks for the idea. I will experients
 A bit if I get it to work in the next days
