### ISSUE TITLE
Opening skill menu error

### ISSUE THREAD

**Issue by Xanderman20** [hannibal00212/SkyHanni#108]
Everytime I open my skill menu i get the error code "SkyHanni caught and logged an NumberFormatException at InventoryOpenEvent." I don't know if this is a bug or if I did something wrong but I would like to know how to fix this.

**Comment by hannibal002** [comment]
Use [Beta 3](https://github.com/hannibal002/SkyHanni/releases/tag/0.18.Beta.3), it should fix the bug
