### ISSUE TITLE
Garden Update/Tweak Spamming "New Visitor"

### ISSUE THREAD

**Issue by itzilly** [hannibal00212/SkyHanni#1159]
Recently, there were a few changes to the garden which is causing the Visitor Tracker system (not too sure the internals) to be wack. This seems to be more apparent when the `Next Visitor` countdown begins.
Chat is constantly spammed with:
```
[SkyHanni] Next Visitor: 1m 6s is visiting your garden!
[SkyHanni] Next Visitor: 1m 3s is visiting your garden!
[SkyHanni] Next Visitor: 1m 1s is visiting your garden!
```

As well as the `New Visitor` message in the middle of the screen being displayed with each chat message.
![image](https://github.com/hannibal002/SkyHanni/assets/90023277/dfb0497f-c90b-45b0-a1eb-29e1f01ad66c)

Steps to reproduce:
1. Install mod (and dependencies)
2. Visit the garden 
3. Farm any crop/afk until the `Next Visitor` message in TAB changes (any value change) 
![image](https://github.com/hannibal002/SkyHanni/assets/90023277/441280d4-2273-42fb-81c0-8d7b8ce18c6e)

This will also display the `New Visitor` across the screen as well.
![image](https://github.com/hannibal002/SkyHanni/assets/90023277/4b96502d-32c0-45d6-8148-47a69f039941)

**Comment by ItsEmpa** [comment]
this issue should be fixed as of the latest beta version

**Comment by CalMWolfs** [comment]
Please make sure you are using the latest beta version of the mod as this has been fixed there for over a week. Also please submit further bug reports on our discord.
