### ISSUE TITLE
Players sometimes invisible

### ISSUE THREAD

**Issue by Bwopp** [hannibal00212/SkyHanni#1200]
This issue seems like a random issue but sometimes when I am playing duels players are invisible, and I painstakingly enabled and disabled every mod in my folder and when I have Skyhanni disabled the issue no longer happens.

**Comment by martimavocado** [comment]
which version are you using? also reporting bugs/getting support on the discord is preferred

**Comment by CalMWolfs** [comment]
Fixed in #1301. Download the beta release or wait a tiny bit for the 0.24 release
