### ISSUE TITLE
Next Visitor: xx xx is detected as a new visitor.

### ISSUE THREAD

**Issue by whitetxt** [hannibal00212/SkyHanni#1265]
Title pretty much explains it all.
The visitor code detects the part of the scoreboard which says "Next Visitor: 00m 00s" as a visitor.
![image](https://github.com/hannibal002/SkyHanni/assets/54776821/43e60439-9220-494f-8c72-c52ea5918ea7)

**Comment by CalMWolfs** [comment]
Please make sure you use up to date versions of mods. This has been fixed for about 3 weeks now. Also please make further bug reports on our discord
