### ISSUE TITLE
Backpack page is not available

### ISSUE THREAD

**Issue by twofigtrees** [hannibal00212/SkyHanni#1280]
Whenever going to the backpack page, both ender chests and backpacks are not accessible.
![image](https://github.com/hannibal002/SkyHanni/assets/165078244/72d3ec29-c62d-4ba7-b3ad-d96ee8fcdcc0)

**Comment by twofigtrees** [comment]
FYI, I have all of the backpack and ender chests slots unlocked.

**Comment by ItsEmpa** [comment]
This is an issue with NEU, not SkyHanni. And this issue is fixed if you use NEU's latest alpha version
