### ISSUE TITLE
Rift Features

### ISSUE THREAD

**Issue by hannibal002** [hannibal00212/SkyHanni#129]
Hide wrong blocks for jump and run (waiting on next alpha opening)

**Comment by CalMWolfs** [comment]
Skytils waypoints for all the places to jump

<Skytils-Waypoint-Data>(V1):H4sIAAAAAAAC/51Yy24bMQz8lXTPLiCSokTm1g/oFxQ5uPWiNZA6geM+0iD/XqVNdlcUvKB8sp0YYz6Gw+E+DV+2p/Hr3XE/PgzXV5+ehsP2+1jeDR/3x+Pd8ed4fBiv7renb8Nm+LV9vL/bH07mm6Tlf7/Lu/cgvBkey7sIm+HPv78E2QzjYfv5dtyVz6fjj3EzbHe7cffhVD5DEiIKEiELPW9mTIgTZtRXTHrDBHRgxgRUYyJNmIktpitOVlUKS8w8hwmvkDhBBgckiAbBJWSCN0wEsuX0pA4QLCbyFCfn/5ikE2ZyxJmQY5064YSZXzFjmHKPDsxMSQmWmDKXky+CBJWIuoTkMJUzgMFUT+YqAlJFCYtqUtN1D5GiSq4x41xNUYuJHiZJjuW16tA8RNkyyZV6fnmpiBSpDZO6iCRSkq/LmRpyLvTD03UGMJgU2tT79COHDPUQxbntShfpnKKgGcwJEtXOpQsSApowgdohwq4WFdRUlxOxlU7sa5GCiZPoPDt92pm5aFIVJ9M87BdJfCmnkFQ6xzpjNpT3TGb5YU31GDG0cXblXr4UkqGntPTELqErlK8lPqbzkL62K6nWWzjRuyl3hKZH0bPfsLzWfc8r9fRwHkJGM5qU12yNS5GBTEFxLmiyy8in8ilZLkFoPMhit3ukDjGa3HkhdfkS+YTAqCbOWer4IqkrnkZjveAmSKLGLrjUExrjOYdJjatxqSdS5hqT5q7LRRYkaxG6em/kVpAncqJnMlMWrMnJ0g4RdgpdiGa359Yqha4h4sLOWpBxFrqkTe6uIZJsDDLBil9wUSkXF2yUrmVSl/sq1Mwmc1jpuq+aglxLJ0lLzj6NL2OJxi6ENs4uwnNKbFZROD9DPpUTLsazvmC4uWAmSVKXR8zCxs/FVuCxK8xUKGwOQpwPwnzJuQEv1ssYkHT+KnIuzFTO06rrKawdrsl1uAZ7b8DKEvbdG4mMSQRp740+dhIH4xFjW85O31nOViPH2PrOrsGEYuOzxCp1bJ9X9ElnEWMyl2sjc4u97rrZMZpHC7y2111PVYjt8RbXDlfPYGphfN31qI1L6tMPzdbM6doDEM8aKuJh+gPaSFJflByjfViRV4rpapAyGEVCbbd639malKU0/WYz7B9ut4eXbw7D883zX4KnNhbkFAAA
