### ISSUE TITLE
Issues with cocoa beans

### ISSUE THREAD

**Issue by NotWhiteRice** [hannibal00212/SkyHanni#1338]
The crop milestone for cocoa beans doesn't update unless I enter the crop milestones UI, my farming weight doesn't update as I farm cocoa beans, and it gives no estimate for how long it would take for me to get into the top 10k while farming cocoa beans; there might be more issues, but I haven't come across them yet.

**Comment by CalMWolfs** [comment]
Hi, please open a bug report on the discord with info such as a recording or steps to reproduce. This is because we deal with all bug reports there and it makes the development process much easier
