### ISSUE TITLE
Jacob's Contest from elitedev.bot are out of sync 

### ISSUE THREAD

**Issue by NotWhiteRice** [hannibal00212/SkyHanni#1339]
I had Fetch Contests enabled, and the timer was off by about a minute and a half. Once I had disabled Fetch Contests and deleted the jacob_contests.json in the config folder, the issue resolved itself, but I had to do the calendar thing.

**Comment by hannibal002** [comment]
Is there a chance your computer time is off by 1.5 minutes as well? Check on https://time.is/
