### ISSUE TITLE
Remove Patcher

### ISSUE THREAD

**Issue by hannibal002** [hannibal00212/SkyHanni#137]
Make SkyHanni no longer require Patcher.
Need to bundle kotlinx libraries in Gradle

Fixing crashes like `java.lang.NoClassDefFoundError: kotlin/collections/MapsKt`

**Comment by NetheriteMiner** [comment]
In my dev environment, I got that after trying to launch with skytils. Hopefully that's a start.

**Comment by hannibal002** [comment]
Fixed in #347
