### ISSUE TITLE
Feature request - Pest repellent timer

### ISSUE THREAD

**Issue by Mahcks** [hannibal00212/SkyHanni#1515]
Hello,

I was wondering if we could get a pest repellent timer so we know when it's about to expire. Have to keep checking the /effects which takes time away from farming.

Thanks!

**Comment by j10a1n15** [comment]
Enable non god pot effects

**Comment by Mahcks** [comment]
> Enable non god pot effects

Did that, thank you for that but now I just see "Night Vision I" I guess I could remove the accessory and just enable full bright.
