### ISSUE TITLE
Anita and Jacob visitors are sometimes not highlighted?

### ISSUE THREAD

**Issue by hannibal002** [hannibal00212/SkyHanni#156]
Unconfirmed that it is definitely just with these 2 visitors.

**Comment by jani270** [comment]
Confirmed https://i.imgur.com/5B6nuGH.jpeg

**Comment by hannibal002** [comment]
Fixed with https://github.com/hannibal002/SkyHanni/commit/d9478299376f302773b59bb0961f2282ab1a03dc
