### ISSUE TITLE
Add SB level + profile type to Discord RPC

### ISSUE THREAD

**Issue by cykq** [hannibal00212/SkyHanni#162]
please add a title of Skyblock Level on discord status, and u can do a small icon is profile challenge, starded or ironman

**Comment by NetheriteMiner** [comment]
I think this would be a good fit with the "Profile Name (Fruit)" option. I'll rename it to "Profile" and just make it say something like "Level 320 on ♲ Lemon" as an example. I don't know if we already have a way to get the player's sb level, though. I might have to make my own (always a terrible idea).

**Comment by NetheriteMiner** [comment]
@6e3DapHocTb Seems to be working, going to test it on bingo as well, but it should be fine. Hypixel refers to regular profiles as classic, for those users who aren't playing any special profile type, would you prefer it say "Level 999 on Lemon" or should it be like "Level 999 on Classic Lemon" or something else?

**Comment by cykq** [comment]
i prefer "SkyBlock Level: [999] on Lemon"
"SkyBlock Level: [999] on ♲Lemon", etc

**Comment by hannibal002** [comment]
Implemented in #234
