### ISSUE TITLE
Can't click on some text in chat

### ISSUE THREAD

**Issue by VacantTarnished** [hannibal00212/SkyHanni#1672]
When I have SkyHanni installed (newest Beta version) I can't click on clickable Text in chat. I couldn't find any settings in the configs so I expect it to be a bug.

## Scenario

I need to click text in chat to start something (like the hotdog eating contest in the rift)  

## What should happen

I should be able to click the text in chat  

## What actually happens

I can't click the text in chat  

## Extra Info

I can still press some text in chat like the SBE daily reminder for heavy pearls. It seems to only be skyblock specific text that I can't click.

**Comment by VacantTarnished** [comment]
Just tested out Beta 19, there I can click on text in chat.

**Comment by hannibal002** [comment]
thanks for reporting
Chat messages like party invite are not clickable with beta 20
this is a known bug, a fix is already in works.
The next time, please report it on discord :)
