### ISSUE TITLE
Chocolate Egg Guesser Breaking

### ISSUE THREAD

**Issue by tendon5** [hannibal00212/SkyHanni#1684]
Whenever the Egg location is shout out with the mod in chat it highlights the egg for all with the mod to go and hunt it. Although If you use the Egglocator item before the chat call out it give you a guess to where the egg is at and marks it. 

The issue I am having is when the egg gets marked from someone in chat and is highlighted then I use the Egglocator it disables the guesser feature of the locator. To get it working again I need to restart the game. 

This only occurs then the egg is found then a locator is used.

Mod Version - SkyHanni-0.25.Beta.19

**Comment by CalMWolfs** [comment]
This is fixed in beta 21, future bug reports should go on the discord
