### ISSUE TITLE
Hoppity solver in dungeons

### ISSUE THREAD

**Issue by TheLeCrafter** [hannibal00212/SkyHanni#1688]
I was playing dungeons with the egglocator in my inventory and a healer in my team. As the healer casts their healing circle, the same green particles as the ones from the egglocator spawn. The hoppity solver then tries to find the egg, so that a waypoint is constantly teleporting back and forth. The solution to this bug would be disabling the solver whilst in dungeons.

**Comment by JeremyMoeglich** [comment]
Related issue, it seems the particle can also occur outside dungeons from players using some rune, here is a screenshot


![2024-05-04_11 24 03](https://github.com/hannibal002/SkyHanni/assets/60170474/31950096-e16c-4d78-9e73-d9536241b6ab)



A solution might be to only look for particles after using egglocator and possibly ignoring particles that aren't in a line originating from the player (though that sounds complicated to implement reliably)

**Comment by CalMWolfs** [comment]
Thanks for the bug report. In future please make these on our discord as that is where we actively track all of our bugs.

#1689 fixes the original issue but not the second issue.
