### ISSUE TITLE
Chat Filter Types, Factory Upgrade not working

### ISSUE THREAD

**Issue by lunicyb** [hannibal00212/SkyHanni#1714]
The Factory upgrade that says it disables the "You have a Chocolate factory upgrade available to purchase!" message from posting in chat but it doesn't. I've tried it on both settings and I've restarted my game multiple times to double check.

![image_2024-05-06_185037611](https://github.com/hannibal002/SkyHanni/assets/65111955/152d765c-c857-4c85-8dbb-920592a964d3)

**Comment by CalMWolfs** [comment]
Use these settings to modify the upgrade warnings, also further bug reports should be made on our discord

![image](https://github.com/hannibal002/SkyHanni/assets/94038482/a4abe117-ff80-42a0-a730-60aad9d3aaf7)
