### ISSUE TITLE
Garden Warp Hotkeys

### ISSUE THREAD

**Issue by hannibal002** [hannibal00212/SkyHanni#203]
3 Hotkeys that only work while inside the garden:

- /warp garden
- /sethome
- /plotteleport <plot name>

the command /plotteleport uses the plot name directly over the center plot, in the image the "Wheat Original" plot (Case sensitive!)

![Image](https://github.com/hannibal002/SkyHanni/assets/24389977/10f7bca6-e3b5-4845-bccf-1240e066b20b)
Has so save the center plot name and edge case if this plot doesn't exist yet

**Comment by CalMWolfs** [comment]
This was mostly added at somepoint
