### ISSUE TITLE
feather client crash

### ISSUE THREAD

**Issue by JoeHoe07** [hannibal00212/SkyHanni#23]
Hey. 
Today i wanted to download the newest version of the mod and put it into the mod folder of feather client which basically works same as 
forge, but unfortunatly the client always crashes when starting. Even trying older versions of Skyhanni didnt work...

**Comment by hannibal002** [comment]
Hey. Feather client is close sourced, meaning I can't fix bugs or add compatibility with Skyhanni for it. If SkyHanni works with forge for you then it's a bug on feather clients side and I can't do anything about it.
I strongly suggest you use normal forge instead anyway.
