### ISSUE TITLE
Garden, Visitor - no time to harvest and price/copper

### ISSUE THREAD

**Issue by Kyrillix** [hannibal00212/SkyHanni#231]
For visitors, the inventory no longer shows the time needed to harvest as well as the price/copper.

**Comment by CalMWolfs** [comment]
will be fixed in #230, for now, you can turn off "Item cost in garden npc" in NEU to make it work again. Also in future please use the #bug-reports channel in the discord

**Comment by hannibal002** [comment]
This issue should be fixed with https://github.com/hannibal002/SkyHanni/releases/tag/0.18.Beta.17.
If it still occures, please tell us on discord
