### ISSUE TITLE
F7/M7 Terminal, device and lever waypoints

### ISSUE THREAD

**Issue by hannibal002** [hannibal00212/SkyHanni#252]
https://discord.com/channels/997079228510117908/1000668251015102515/1121479216320487535

**Comment by parallelmedias** [comment]
Do you want this added?

**Comment by hannibal002** [comment]
I think this feature already got addet to another mod since this issue got created.

**Comment by CalMWolfs** [comment]
I thought it's only in soopy unless it's in dsm or volc addons as I'm not familiar with those two

**Comment by CalMWolfs** [comment]
#2719
