### ISSUE TITLE
No way to change the location of Estimated Item Value

### ISSUE THREAD

**Issue by strangerpng** [hannibal00212/SkyHanni#264]
There is no way to change the location of Estimated Price - it doesn't show up in the GUI Location settings, and there is no option to change its location in the dropdown menu for the feature. By default, the value text is obstructed by the inventory. 
Demonstrating the issue: https://youtu.be/J4OpZUGPFq4

**Comment by CalMWolfs** [comment]
Please ask for support on the discord first. There is also a message while editing gui telling you how to do this and people in the discord to help you

**Comment by strangerpng** [comment]
I actually feel illiterate now, don't know how i missed it. Apologies for opening a useless issue
