### ISSUE TITLE
A crash?

### ISSUE THREAD

**Issue by Neotro3636** [hannibal00212/SkyHanni#31]
It crashes and it says...
![image](https://user-images.githubusercontent.com/81803489/229878753-5b2f0a78-ce6c-46e8-8503-059eea1b4f50.png)
Can't find neu 2.1.1 ver instead of 2.1.0 from websites

**Comment by Jason54jg** [comment]
download neu alpha 
https://github.com/NotEnoughUpdates/NotEnoughUpdates/releases/tag/v2.1.1-alpha12

**Comment by Neotro3636** [comment]
that hits the spot, thank you

**Comment by jani270** [comment]
Solved
