### ISSUE TITLE
Outline style?

### ISSUE THREAD

**Issue by Neotro3636** [hannibal00212/SkyHanni#32]
the mod might be better with overlay style for readability, i guess.
like one of the neu settings 
![Screenshot 2023-04-05 0930382](https://user-images.githubusercontent.com/81803489/229954198-3452d446-97f9-4d18-aead-2b069437c913.png)

**Comment by hannibal002** [comment]
That is already planned. Thanks for the idea.
For further ideas, please use the discord instead:
https://discord.gg/nnf4vCMd
