### ISSUE TITLE
Minion tier show with no minion

### ISSUE THREAD

**Issue by Turadim** [hannibal00212/SkyHanni#322]
If i remove a minion its still shows me which minion was there. 
![2023-07-17_18 11 04](https://github.com/hannibal002/SkyHanni/assets/139793876/26c9b345-63d2-47b0-91a4-a9373f95d8b3)

**Comment by NetheriteMiner** [comment]
Do /shclearminiondata, assuming you're up to date...?

**Comment by Turadim** [comment]
yea thanks that solves the problem
