### ISSUE TITLE
Unexpected health of thorn in f4 message spam

### ISSUE THREAD

**Issue by StarZebra** [hannibal00212/SkyHanni#329]
While in f4 boss and thorns gets a weird health skyhanni starts spamming that.
[spam](https://i.imgur.com/HqjfP2S.png)

**Comment by hannibal002** [comment]
This is strange. The health should be 66k instead. Do you have any idea what caused the different health numbers?
https://github.com/hannibal002/SkyHanni/blob/fc6e7c4d7c7d4c535141c1bb15225e0f98660894/src/main/java/at/hannibal2/skyhanni/features/damageindicator/DamageIndicatorManager.kt#L651

**Comment by CalMWolfs** [comment]
Bug and cause already listed on the discord

**Comment by StarZebra** [comment]
mb im not in the discord 
also maybe you should add a check to see it its enabled, cuz i have it disabled rn and its still spamming

**Comment by hannibal002** [comment]
If we didn't show such error messages when the function is disabled, we wouldn't find them so quickly. So in this case it helped us. ;)

The comment in discord about where the damage difference comes from was written because you raised the issue! Thank you for that!

**Comment by StarZebra** [comment]
That is true, well good luck on fixing it. :)

**Comment by hannibal002** [comment]
It should be fixed with https://github.com/hannibal002/SkyHanni/commit/9dc0642c483f3f74297ebf6bdb6dc1dae8ac3679 hopefully
