### ISSUE TITLE
Minion Name tag not disappearing after removing the minion

### ISSUE THREAD

**Issue by Prathamisgreat** [hannibal00212/SkyHanni#343]
When you turn the "Minion Name Display" feature the minions name shows on top of its head but when removing the minion sometimes the text doesn't go away. This creates scenarios like this where there are multiple texts without the minion.
![2023-07-28_19 37 34](https://github.com/hannibal002/SkyHanni/assets/96686111/55ec07c9-5a64-4d71-af09-3afbbcdbed2b)

**Comment by superhize** [comment]
You need to run /shclearminiondata

It's gonna reset data about minion profit and the name display

**Comment by brandonwamboldt** [comment]
Fixed in [0.20 Beta 17](https://github.com/hannibal002/SkyHanni/commit/a1b308e3c51a500cdd308cbc8605678dd13c538f). For existing nametags, you'd need to run /shclearminiondata or place a minion in the same place and then pick it up again
