### ISSUE TITLE
Visitor drops stats

### ISSUE THREAD

**Issue by YayL** [hannibal00212/SkyHanni#355]
When you receive an overgrown grass, the "Coins Spent" section of the visitor statistics will add, what I am assuming to be, the current price of that item to the "Coins Spent." This seems like incorrect behavior.

**Comment by YayL** [comment]
I'm not very versed with your code base. However, I assume the drawToolTip function on line 375 causes this.
As you are using the global private variable price in this instance then when the for loop has iterated over the entire tooltip the last value that the price is set to is the value of the overgrown grass as that is the last instance of the correct item format. This results in the `itemName != null` to be true. When the user then accepts the visitor the line on 294 will use this value of the overgrown grass to increase the GardenVisitorDropStatistics.coinsSpent variable

**Comment by YayL** [comment]
I think that there might also be issues in cases where there are multiple crops requested by the visitor. I think this can be fixed by removing the current `totalPrice = price` on line 382 and adding the line `totalPrice += price` after the if statement

**Comment by YayL** [comment]
Forgot to say that my proposed soloution to this would be to add a boolean flag for whether we have passed the "rewards:" line. Then just replace the `totalPrice == 0` with `rewardFlag` meaning that it is set to true initially but changed to false after passing the "rewards:" line and to fix the other proposed problem just change the `totalPrice = price` to `+=`

**Comment by parallelmedias** [comment]
I've added in the totalPrice += price you proposed, but am unsure where you would create a flag for passing the rewards line.

Your code lines also are different than mine so a sample snippet would be beneficial

Is there any way to test a overgrown grass to verify the error has been fixed then?
![image](https://github.com/hannibal002/SkyHanni/assets/47892459/63ee3655-f5cc-4e81-b06f-e884e90cad37)

**Comment by hannibal002** [comment]
This bug got fixed in [#beta](https://github.com/hannibal002/SkyHanni/releases/tag/0.20.Beta.13)
