### ISSUE TITLE
neu needs to be 2.1.1 but there is no neu 2.1.1

### ISSUE THREAD

**Issue by Ghostly187** [hannibal00212/SkyHanni#36]
When i put skyhanni in my mods folder it says neu needs to be atleast version 2.1.1 but there isnt a neu version 2.1.1 theres only 2.1.0
![image_2023-04-11_154157289](https://user-images.githubusercontent.com/130479631/231198921-beab4b1c-5824-4c55-8e72-92babc237932.png)

**Comment by hannibal002** [comment]
Yes, there is: https://github.com/NotEnoughUpdates/NotEnoughUpdates/releases

**Comment by Ghostly187** [comment]
oh thank you i spent a while trying to find it
