### ISSUE TITLE
minecraft crashing 

### ISSUE THREAD

**Issue by marcriana** [hannibal00212/SkyHanni#370]
it says i havent downloaded the newest version of skyhanni even though i have

**Comment by hannibal002** [comment]
Read the error message again please :)

You need the latest version of NotEnoughUpdates!

**Comment by marcriana** [comment]
i do have the latest version of neu though...

**Comment by hannibal002** [comment]
Send a Screenshot of the error message you get.
And of your mods folder please

**Comment by CalMWolfs** [comment]
Can we discuss this in the discord?

**Comment by marcriana** [comment]
ok, which channel should we discuss it in?

**Comment by jani270** [comment]
This issue should be discussed in the discord under #support

**Comment by hannibal002** [comment]
https://discord.gg/YYHBeYCm
