### ISSUE TITLE
Suggestion: Move the item amount after the fished up item

### ISSUE THREAD

**Issue by derNiklaas** [hannibal00212/SkyHanni#399]
Instead of "+ x2 Raw Fish" it should display "+ Raw Fish x2", with the x2 in dark grey instead of normal grey. This would make it inline with the normal Hypixel shop inventory and imo easier to read

**Comment by hannibal002** [comment]
I have tested it.
Are you convinced this gray text is better readable?
![image](https://github.com/hannibal002/SkyHanni/assets/24389977/95ae5980-1929-4e9a-b045-b08b495e1e5a)
@derNiklaas

**Comment by derNiklaas** [comment]
Oh, Ive only looked at it via Minecraft chat and not having a background. the lighter gray is def. better in that case

**Comment by hannibal002** [comment]
The dark gray color is good for item lore, not for inside the world. sadly.
