### ISSUE TITLE
Price Website option under Bazaar category bugged

### ISSUE THREAD

**Issue by AtomicShadow2006** [hannibal00212/SkyHanni#466]
When this option is on, the button to show the price history on skyblock.bz shows up twice: once under the item in the bazaar menu, as it should be, and once in the middle of your inventory. The correct one functions just fine, however, the one in the inventory seems to be a visual bug as it doesnt do anything and it (visually) overrides whatever is in that slot

<img width="554" alt="image" src="https://github.com/hannibal002/SkyHanni/assets/102123152/4b33f587-a39e-4d12-8df7-3421bde38ede">

**Comment by CalMWolfs** [comment]
Thanks for reporting, the fix has already been made and will be in 0.20 beta 20. In future please report bugs on [the discord](https://discord.gg/skyhanni-997079228510117908)
