### ISSUE TITLE
Garden milestones seem to be bugged 

### ISSUE THREAD

**Issue by StefanUAIC** [hannibal00212/SkyHanni#493]
I'm not really sure why, but for example there was an update to the garden milestones and for Wheat at milestone 21 I'm being told I have to get 2 million wheat which is wrong, because the correct amount is 660k. Also, when I open the milestone menu, it briefly updates to 500k, which is also wrong, then goes back to 2 million afterwards (when collecting wheat). This bug might be occurring for other crops as well

**Comment by CalMWolfs** [comment]
Make sure you use the betas for the updated crop milestone values. If this still does not work report further issues on the discord

**Comment by StefanUAIC** [comment]
Yea you were right, I wasn't updated to the newest version, closing issue thanks
