### ISSUE TITLE
[BUG] Jacob Items are not shown correctly

### ISSUE THREAD

**Issue by Helfull** [hannibal00212/SkyHanni#533]
![image](https://github.com/hannibal002/SkyHanni/assets/720645/95d747bf-43ed-434b-9cfd-e6e590d48d18)

It was new year and then it started breaking, now it is out of sync, after it did download the data from `elitebot.dev`

I tried to delete the `gardenJacobFarmingContestTimes` data from the config, but it does just get filled with the same data.

**Comment by ptlthg** [comment]
This is a known bug, we think the update today changed the calendar after it was already uploaded to elitebot.dev which has caused people to pull in the wrong data.

It's been corrected already on the website, so any new request should give the correct data. 

Are you sure that you reset it properly? The contests line up on https://elitebot.dev/contests/upcoming which uses the same source that SkyHanni fetches from.

I think SkyHanni could have a better way to reset stored contests though if this happens again regardless though.

**Comment by hannibal002** [comment]
Hey, thanks for reporting this bug.
Seems like Hypixel has changed the contests during the year. 😕 

You can try to run this command:
`/shconfig reset config.storage.gardenJacobFarmingContestTimes`
Then rejoin the garden. If that doesn't reload the crops, restart your game.

In the future, please report bugs directly on our discord: https://discord.gg/skyhanni-997079228510117908
