### ISSUE TITLE
f key not working after downloading skyhanni

### ISSUE THREAD

**Issue by ygolomeg** [hannibal00212/SkyHanni#663]
prior to downloading the mod, i use the f key to change perspective, however, now after downloading the mod, my f key does not do anything in game, and does not allow me to change perspective.

There are no conflicting controls on the Minecraft controls panel, as it would be highlighted in red, and I checked through the entire mod options on skyhanni, but could not find anything that uses 'f' key

any help to fixing this is appreciated thanks

**Comment by cimbraien** [comment]
I don't think SkyHanni bind "F" key to any feature by default, but I see NEU is using it for `Set item to favourite`. Did you install NEU for the first time as well? If so, this might be the case.

**Comment by hannibal002** [comment]
Closed due to inactivity.
