### ISSUE TITLE
ItemResolutionQuery returns null

### ISSUE THREAD

**Issue by BluePotatoBP** [hannibal00212/SkyHanni#78]
I get these errors by holding a cane hoe: 

"ItemResolutionQuery returns null for internalName 'COMPOST'"
"SkyHanni caught and logged an RuntimeException at TabListUpdateEvent"

More than happy to provide logs if needed.

**Comment by BluePotatoBP** [comment]
Hey man, I see you've responded to all other issues... I feel left out 🥲

**Comment by hannibal002** [comment]
Hey, sorry for the wait. Please try /neuresetrepo

**Comment by BluePotatoBP** [comment]
Sorry for making you wait this time, I did /neuresetrepo
![image](https://user-images.githubusercontent.com/52742857/236706160-b7c62b5a-a2f6-47e8-8db9-cf067586678e.png)
Still getting the errors.

**Comment by BluePotatoBP** [comment]
Turns out I had to manually download the repo and extract it into the neu config folder. Sorry!

**Comment by itsjusttriz** [comment]
> Turns out I had to manually download the repo and extract it into the neu config folder. Sorry!

Please tell me what you did to fix this. Im getting it everytime I open any of my Sacks

**Comment by BluePotatoBP** [comment]
From mulberry discord:

Step 1: Download the repo at  - https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/archive/refs/heads/master.zip
Step 2: Extract the repo and copy its content - https://i.imgur.com/xsQkqum.png
Step 3: Navigate to .minecraft/config/notenoughupdates/
Step 4: Create a repo folder if there are none.
Step 5 : Paste the content you just previously copied
Step 6 : The final results should look like this - https://i.imgur.com/leKyhuA.png
