### ISSUE TITLE
Composter estimates are no longer accurate.

### ISSUE THREAD

**Issue by NotWhiteRice** [hannibal00212/SkyHanni#799]
The recent update changed how much compost boxes of seeds make.

**Comment by lunaynx** [comment]
Did it? It's still worth 25,600 organic matter.

**Comment by jani270** [comment]
![image](https://github.com/hannibal002/SkyHanni/assets/69345714/655ad197-38c3-487c-ba06-7b00f690d015)
Fake news. Also please use the bug reports channel in our discord

**Comment by NotWhiteRice** [comment]
I bought a box of seeds, since the mod told me I only needed one, but it barely filled up the bar at all.

**Comment by j10a1n15** [comment]
Please use the discord bug reports channel
