### ISSUE TITLE
No chat messages for some NPCs

### ISSUE THREAD

**Issue by b1n4ryj4n** [hannibal00212/SkyHanni#88]
Hi there with the Beta 40 i get no more NPC chat messages.

For example Fetchur or the Trial of Campfire NPC wont show up the needed stuff.

I tried to disable all chat filtering features but it still wont show up.

I went back to 39.1 and all works fine - i guess there is a bug in Beta 40 -.

**Comment by hannibal002** [comment]
Hey, can you contact me on discord please?
https://discord.gg/JVptxxbz

**Comment by hannibal002** [comment]
The bug is fixed in 0.17
