### ISSUE TITLE
no chat messages at all 

### ISSUE THREAD

**Issue by Marcodyle** [hannibal00212/SkyHanni#89]
no chat massege at all after 5m in the game
i log in and chat messages appers and all good then after 5m all messages diappers and i can't see any messages including my messages

**Comment by hannibal002** [comment]
The bug is already known. As a workaround, you can disable the bingo compact chat feature.

**Comment by jani270** [comment]
Fixed in https://github.com/hannibal002/SkyHanni/commit/721b39af021c2cd60abb81c663a11d54ab742f3e
