### ISSUE TITLE
False SkyHanni error

### ISSUE THREAD

**Issue by GamerNDS** [hannibal00212/SkyHanni#954]
SkyHanni 'detects' that I am using NEU 2.1, which is not the latest version. While it is true that NEU 2.1 is not the latest version, I am using version 2.1.1 alpha 26, not 2.1.

Image for context:
![image](https://github.com/hannibal002/SkyHanni/assets/65942033/c0624f0f-3b4e-4f25-98cf-73c341fb4b21)

**Comment by RayDeeUx** [comment]
a) which version of skyhanni did you have when taking this screenshot
b) please take further inquires here: https://discord.com/channels/997079228510117908/1136431234717855918

**Comment by hannibal002** [comment]
The error message is not telling you that you use the wrong version. It tells you you don't have NEU at all. Check that you use the correct mods folder for both mods.
